### ISSUE TITLE
failed to build 

### ISSUE THREAD

**Issue by dd4g12** [StartBootstrap/startbootstrap-clean-blog-jekyll#266]
Hi,
I managed to use this theme few months ago. I updated the website and had no issues locally but now I can't publish the  updates. I get the following build error.

GitHub Pages failed to build your site.

Your SCSS file assets/main.scss has an error on line 5: File to import not found or unreadable: ../node_modules/bootstrap/scss/bootstrap. Load paths: /tmp/jekyll-remote-theme-20210430-6-etgmlz/_sass /tmp/jekyll-remote-theme-20210430-6-etgmlz/_sass /tmp/jekyll-remote-theme-20210430-6-etgmlz/_sass.

**Comment by budalokko** [comment]
Same error here on a fresh install in my local environment. Issuing following commands before `bundle install` solved it without changing any line in the code:

```
npm update
npm install
```
I am sorry I can't explain the reasons or what should be done. I am only testing this jekyll thingie :smile:

**Comment by tadx-group** [comment]
Hi, same issue for me.
How fix the GitHub deployment problem ?

**Comment by Funniest** [comment]
i tried below commands.
As a result was fixed that bug
```
npm update
npm install
```

my full log message
```
C:\Users\admin\Desktop\Projects\funniest.github.io>jekyll build
Resolving dependencies...
Configuration file: C:/Users/admin/Desktop/Projects/funniest.github.io/_config.yml
            Source: C:/Users/admin/Desktop/Projects/funniest.github.io
       Destination: C:/Users/admin/Desktop/Projects/funniest.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/main.scss':
                    Error: File to import not found or unreadable: ../node_modules/bootstrap/scss/bootstrap. on line 5:1 of assets/vendor/startbootstrap-clean-blog/scss/styles.scss from line 2:1 of _sass/styles.scss from line 1:1 of main.scss >> @import "../node_modules/bootstrap/scss/bootstrap"; ^
                    ------------------------------------------------
      Jekyll 4.2.0   Please append `--trace` to the `build` command
                     for any additional information or backtrace.
                    ------------------------------------------------
Traceback (most recent call last):
        29: from C:/Ruby27-x64/bin/jekyll:23:in `<main>'
        28: from C:/Ruby27-x64/bin/jekyll:23:in `load'
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/exe/jekyll:15:in `<top (required)>'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `each'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:36:in `process'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:65:in `build'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:28:in `process_site'
        14: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:80:in `process'
        13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:211:in `render'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:538:in `render_pages'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:538:in `each'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:539:in `block in render_pages'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:547:in `render_regenerated'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:63:in `run'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:84:in `render_document'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:104:in `convert'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:104:in `reduce'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:104:in `each'
         3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:106:in `block in convert'
         2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:185:in `convert'
         1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/sassc-2.4.0-x64-mingw32/lib/sassc/engine.rb:50:in `render'
C:/Users/admin/Desktop/Projects/funniest.github.io/assets/vendor/startbootstrap-clean-blog/scss/styles.scss:5: Error: File to import not found or unreadable: ../node_modules/bootstrap/scss/bootstrap. (SassC::SyntaxError)
        on line 5:1 of assets/vendor/startbootstrap-clean-blog/scss/styles.scss
        from line 2:1 of _sass/styles.scss
        from line 1:1 of main.scss
>> @import "../node_modules/bootstrap/scss/bootstrap";

   ^
        28: from C:/Ruby27-x64/bin/jekyll:23:in `<main>'
        27: from C:/Ruby27-x64/bin/jekyll:23:in `load'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/exe/jekyll:15:in `<top (required)>'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `each'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:36:in `process'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:65:in `build'
        14: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:28:in `process_site'
        13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:80:in `process'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:211:in `render'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:538:in `render_pages'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:538:in `each'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:539:in `block in render_pages'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:547:in `render_regenerated'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:63:in `run'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:84:in `render_document'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:104:in `convert'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:104:in `reduce'
         3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:104:in `each'
         2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:106:in `block in convert'
         1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:182:in `convert'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:190:in `rescue in convert': Error: File to import not found or unreadable: ../node_modules/bootstrap/scss/bootstrap. (Jekyll::Converters::Scss::SyntaxError)
        on line 5:1 of assets/vendor/startbootstrap-clean-blog/scss/styles.scss
        from line 2:1 of _sass/styles.scss
        from line 1:1 of main.scss
>> @import "../node_modules/bootstrap/scss/bootstrap";

   ^

C:\Users\admin\Desktop\Projects\funniest.github.io>npm update
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm WARN bootstrap@4.6.0 requires a peer of popper.js@^1.16.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ jquery@3.6.0
+ font-awesome@4.7.0
+ bootstrap@4.6.0
+ startbootstrap-clean-blog@5.1.0
added 193 packages from 253 contributors and audited 194 packages in 3.701s

7 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


C:\Users\admin\Desktop\Projects\funniest.github.io>npm install
npm WARN bootstrap@4.6.0 requires a peer of popper.js@^1.16.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 194 packages in 0.781s

7 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


C:\Users\admin\Desktop\Projects\funniest.github.io>
C:\Users\admin\Desktop\Projects\funniest.github.io>
C:\Users\admin\Desktop\Projects\funniest.github.io>
C:\Users\admin\Desktop\Projects\funniest.github.io>jekyll build
Configuration file: C:/Users/admin/Desktop/Projects/funniest.github.io/_config.yml
            Source: C:/Users/admin/Desktop/Projects/funniest.github.io
       Destination: C:/Users/admin/Desktop/Projects/funniest.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
                    done in 0.292 seconds.
 Auto-regeneration: disabled. Use --watch to enable.

C:\Users\admin\Desktop\Projects\funniest.github.io>jekyll serve
Configuration file: C:/Users/admin/Desktop/Projects/funniest.github.io/_config.yml
            Source: C:/Users/admin/Desktop/Projects/funniest.github.io
       Destination: C:/Users/admin/Desktop/Projects/funniest.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
                    done in 0.296 seconds.
 Auto-regeneration: enabled for 'C:/Users/admin/Desktop/Projects/funniest.github.io'
    Server address: http://127.0.0.1:4000/startbootstrap-clean-blog-jekyll/
  Server running... press ctrl-c to stop.
```

**Comment by Funniest** [comment]
You can try compile in your local computer.
The compile result is ___site__ folder.
You copy files in _site folder to your github.io repository, and git push that.

**Comment by philippart-s** [comment]
With GH pages the compilation and deployment are managed by GH not in the local machine, your trick can't be applied

**Comment by Funniest** [comment]
I don't know why it can't build origin files...TT

My trick is )
I think github build ignored jekyll-paginate-v2.
It's solutions that using other github repository.
Like, makes 2 repository type of blog repository for build and github.io repository for build result of _site.
Next step is using CI in github in build repository.
You set this setting automatically build to github.io repository.

**Comment by philippart-s** [comment]
I don't say your trick doesn't work, I say it's not my use case. 😉 
I need / want to keep the same repo as jekyll sources and GH hosting, I'm using GH pages for this kind of use (no need to configure CI).

**Comment by dd4g12** [comment]
@davidtmiller any ideas how can we solve this issue?
Thanks

**Comment by skoofer** [comment]
Same problem here. Using github pages and I started to receive this error. Any ideas?

![image](https://user-images.githubusercontent.com/12249168/117569641-e8c26800-b0c6-11eb-889f-ee3467d48562.png)

**Comment by skoofer** [comment]
I was able to workaround the issue for now until the owner fixes it properly.

As far as I can see, the latest [commit done 10 days ago](https://github.com/StartBootstrap/startbootstrap-clean-blog-jekyll/commit/78e9feaae106b49b51f520d0a3a07bf701744d7a) broke this theme.
For now,
If you are using Jekyll themes, install the previous version instead of using the most recent (broken) version 4.0.11
`gem "jekyll-theme-clean-blog", "4.0.10"`

If you are using Github Pages via remote_theme, you could have specified the previous version via StartBootstrap/startbootstrap-clean-blog-jekyll@4.0.10; but this repo does not have Tags/Releases. Therefore you need to directly get the remote theme via the git ref of the previous commit on master (workaround). If you do this in your _config.yaml for the time being , it will work:
`remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll@2b27cc8aa52234f701af0847d7969fdc019ae4fd`

**Comment by davidtmiller** [comment]
I just ran the `npm update` and `npm install` in the repo and pushed to `gh-pages`

I will see if I have any compile errors from GitHub Pages. Working on a fix now!

**Comment by davidtmiller** [comment]
I found the issues. The SCSS in the base Clean Blog theme is pulling in Bootstrap from `node_modules` but the Bootstrap SCSS, when uses Jekyll, needs to be local to the project. I have manually put the Bootstrap SCSS in the `assets/vendor/scss` directory and it is working now.

Sorry for the hiccup all!

Fixed in b17ce47e4153d439d28513866ce3f17bdf627de2

**Comment by skoofer** [comment]
GH Pages builds fine now, thanks @davidtmiller !

**Comment by dd4g12** [comment]
@davidtmiller It works thanks
